apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: broadcaster-patch.yaml

images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/broadcaster
  newTag: a1d64da298c2d01a165d19d9e54ab59dc4bb9e59
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-app
  newTag: a1d64da298c2d01a165d19d9e54ab59dc4bb9e59
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-backend
  newTag: a1d64da298c2d01a165d19d9e54ab59dc4bb9e59
