apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/persistentvolumeclaim.yaml

  - applications/project/manifests/configmap.yaml
  - applications/project/manifests/service.yaml
  - applications/project/manifests/deployment.yaml
  - applications/project/manifests/cronjob.yaml
  - applications/project/manifests/ingress.yaml

  - applications/todo-backend/manifests/postgres.yaml
  - applications/todo-backend/manifests/service.yaml
  - applications/todo-backend/manifests/deployment.yaml

images:
  - name: PROJECT/TODO_APP
    newName: reyver/todo-app
    newTag: 3.5-amd64

  - name: PROJECT/TODO_BACKEND
    newName: reyver/todo-backend
    newTag: 3.5-amd64
