apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/persistentvolumeclaim.yaml
- applications/todo-backend/manifests/backup-cronjob.yaml
- applications/project/manifests/configmap.yaml
- applications/project/manifests/service.yaml
- applications/project/manifests/deployment.yaml
- applications/project/manifests/cronjob.yaml
- applications/project/manifests/ingress.yaml
- applications/broadcaster/manifests/deployment.yaml
- applications/todo-backend/manifests/postgres.yaml
- applications/todo-backend/manifests/service.yaml
- applications/todo-backend/manifests/deployment.yaml



images:
- name: PROJECT/BROADCASTER
  newName: reyver/broadcaster
  newTag: "4.8"
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-app
  newTag: 3aea3700cce1e97aa1934a3b27b4f950c1524266
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/devops-course-503807/dwk-images/todo-backend
  newTag: 3aea3700cce1e97aa1934a3b27b4f950c1524266
